from typing import Protocol, Sequence
from ..entities.book import Book

class BookRepository(Protocol):
    async def add(self, book: Book) -> Book: ...
    async def get(self, id_: int) -> Book | None: ...
    async def get_by_isbn(self, isbn_norm: str) -> Book | None: ...
    async def list(self, skip: int, limit: int, q: str | None) -> Sequence[Book]: ...
    async def update(self, book: Book) -> Book: ...
    async def delete(self, id_: int) -> None: ...
