from typing import Protocol
from ... domain.repositories.book_repository import BookRepository

class UnitOfWork(Protocol):
    books: BookRepository
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...
    async def commit(self): ...
    async def rollback(self): ...
